---
- name: apt-get update
  apt: update_cache=yes

- name: Install required packages
  apt:
    pkg={{ item }}
    state=latest
  with_items:
    - python-pip
    - python-dev
    - python-xmpp
    - build-essential
    - firefox

- name: upgrade pip
  shell: pip install --upgrade pip

- name: upgrade virtualenv
  shell: pip install --upgrade virtualenv

- name: Install robot framework with pip
  pip:
    name={{ item }}
    state=present
  with_items:
    - robotframework
    - robotframework-selenium2library


