---
- name: apt-get update
  apt: update_cache=yes

- name: create folder
  action: command mkdir -p /usr/local/selenium creates=/usr/local/selenium
  register: created_directory   

- name: download Selenium Grid (Selenium Server)
  get_url: url=http://selenium-release.storage.googleapis.com/2.42/selenium-server-standalone-2.42.0.jar dest=/usr/local/selenium/selenium-server-standalone-2.42.0.jar

- name: Install required packages
  apt:
    pkg={{ item }}
    state=latest
  with_items:
    - default-jre
    - python-pip
    - python-dev
    - python-xmpp
    - build-essential
    - firefox
    - xvfb

- name: upgrade pip
  shell: pip install --upgrade pip

- name: upgrade virtualenv
  shell: pip install --upgrade virtualenv

- name: Install robot framework with pip
  pip:
    name={{ item }}
    state=present
  with_items:
    - robotframework
    - robotframework-selenium2library

#TODO!!
# start if  hub:
#java -jar selenium-server-standalone-2.42.0.jar -role hub
# start if slave
#java -jar selenium-server-standalone-2.42.0.jar -role node -hub http://<hub_url>:<hub_port>/grid/register 

